Blog\DomainBundle\Entity\Post:
    type: entity
    table: post
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
        text:
            type: text
        created:
            type: datetime
    manyToOne:
        author:
            targetEntity: User
            inversedBy: posts
