Blog\DomainBundle\Entity\Post:
    type: entity
    table: post
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        text:
            type: text
    manyToOne:
        author:
            targetEntity: User
            inversedBy: posts
