Blog\DomainBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        login:
            type: string
            length: 64
        passwordHash:
            type: string
            length: 64
    oneToMany:
        posts:
            targetEntity: Post
            mappedBy: author
            cascade: ["persist", "remove"]
