parameters:
#    blog_domain.example.class: Blog\DomainBundle\Example

services:
    domain.doctrine.queryFactory:
        class: Blog\DomainBundle\Doctrine\QueryFactory
        arguments: [@doctrine]

    domain.service.user:
        class: Blog\DomainBundle\Service\UserService
        arguments: [@doctrine, @domain.doctrine.queryFactory, @logger]

    domain.service.post:
            class: Blog\DomainBundle\Service\PostService
            arguments: [@doctrine, @domain.doctrine.queryFactory, @logger]
