parameters:
#    blog_frontend.example.class: Blog\FrontendBundle\Example

services:
#    blog_frontend.example:
#        class: %blog_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
